name: task_manager
environment:
  sdk: '^3.7.0'
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: '^3.5.6'
  enven: '^1.2.1'
  dart_jsonwebtoken: ^3.2.0
  bcrypt: ^1.1.3
  http: ^1.4.0
